### ISSUE TITLE
Inconsistent German translation of "Bruisers"

### ISSUE THREAD

**Issue by cinnamon189** [vcmi-mods/forge2k#2]
Bruisers are referred to as "Bombardiere" in the unit bar and recruitment dialogues, but as "Kanonier-Offiziere" in the Town Hall and as "Kanonier-Kapitäne" in the description of Rengust's special ability. Please check which term is the correct one and make the translation consistent. Please also check the German term used for Bruisers as wandering monsters.

I'm playing VCMI 1.2.1 with Himmlische Schmiede 2000 2.000

**Comment by heroesiiifan** [comment]
Do you have any suggestions what's the best translation?

There are no official ("correct") translation. So we have to choose the best fitting one.

You can find the translation here: https://github.com/vcmi-mods/forge2k/blob/vcmi-1.3/Forge2k/Content/translation/forge2k/german.json
Feel free to optimize if you want. :)

**Comment by cinnamon189** [comment]
Thank you for the link 🙂 Hmm... Maybe "Bazooka-Schützen" and "Bazooka-Veteranen"? Next week I'll have more time to think about it.
